### ISSUE TITLE
tcp_nodelay should enable or disable?

### ISSUE THREAD

**Issue by pernghh** [silviucpp/erlcass#29]
Hi 
I am checking the tcp_nodelay setting, I found that in sample, tcp_nodelay is setting to true ({tcp_nodelay, true}).
But in wiki page. The description of tcp_nodelay is {tcp_nodelay, false} and said  
Default: true (disabled). 
I am a little confusing about this setting. The ture means disable tcp_nodelay?
If I want tcp sent packet ASAP. Should I use {tcp_nodelay, false} or {tcp_nodelay, true}?

Thank you~~

**Comment by silviucpp** [comment]
I have no idea why you are confused because the documentation is pretty clear if you know a little about the TCP stack. By default TCP uses Nagle's algorithm to collect small outgoing packets to send all at once.

The default value of `tcp_nodelay` is `true` which means Nagle's algorithm it's disabled. (for this reason the documentation says "Default: true (disabled).")

In wiki where you see it false, it's just an example of a valid value : "Example: {tcp_nodelay, false}"

So if you want to disable Nagle's algorithm use it true, if you want to keep it enable put it false.

Silviu
