### ISSUE TITLE
build_deps.sh overriding libuv install in Ubuntu 16.04

### ISSUE THREAD

**Issue by goncalotomas** [silviucpp/erlcass#31]
Hi!

I'm updating my TravisCI config file, and I'm using the Xenial Ubuntu (16.04) environment. This environment already comes with the correct libuv version (v1 instead of v0), however, in my Travis executions, I see that upon running `build_deps.sh` my existing version is downgraded to v0 in some weird way. Is it possible that, like for the CentOS configuration, you could add a check that verifies if libuv is available and only proceed if it's not?

It would be invaluable for me to get this working without rough edges :)

Thanks,

**Comment by goncalotomas** [comment]
Just in case I'm looking at this from the wrong perspective, I got this impression from my travis build log:
https://travis-ci.org/goncalotomas/FMKe/builds/455202064#L594-L668

**Comment by goncalotomas** [comment]
In fact, I suspect that just changing the code here:
https://github.com/silviucpp/erlcass/blob/master/build_deps.sh#L52
And replacing `libuv-dev` for `libuv1-dev` might be enough to fix it.

**Comment by silviucpp** [comment]
I think just removing `sudo apt-add-repository -y ppa:linuxjedi/ppa` will fix your problem. I don't know if anyone still using Ubuntu < 16.04 (I'm not). Because removing that might break 14.04.

I don't have this days time to look into this and test on both 14.04 and 16.04 but I'll look at some point.
